// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Survey struct {
	ID          string             `json:"id"`
	Title       string             `json:"title"`
	Description *string            `json:"description"`
	Questions   []byte             `json:"questions"`
	Status      string             `json:"status"`
	OwnerID     string             `json:"owner_id"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type SurveyResponse struct {
	ID        string             `json:"id"`
	SurveyID  string             `json:"survey_id"`
	Answers   []byte             `json:"answers"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type User struct {
	ID           string             `json:"id"`
	Email        string             `json:"email"`
	Name         *string            `json:"name"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}
