// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: query.sql

package db

import (
	"context"
)

const createSurvey = `-- name: CreateSurvey :one
INSERT INTO surveys (title, description, questions, owner_id)
VALUES ($1, $2, $3, $4)
RETURNING id, title, description, questions, status, owner_id, created_at, updated_at
`

type CreateSurveyParams struct {
	Title       string  `json:"title"`
	Description *string `json:"description"`
	Questions   []byte  `json:"questions"`
	OwnerID     string  `json:"owner_id"`
}

func (q *Queries) CreateSurvey(ctx context.Context, arg CreateSurveyParams) (Survey, error) {
	row := q.db.QueryRow(ctx, createSurvey,
		arg.Title,
		arg.Description,
		arg.Questions,
		arg.OwnerID,
	)
	var i Survey
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Questions,
		&i.Status,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createSurveyResponse = `-- name: CreateSurveyResponse :one
INSERT INTO survey_responses (survey_id, answers)
VALUES ($1, $2)
RETURNING id, survey_id, answers, created_at
`

type CreateSurveyResponseParams struct {
	SurveyID string `json:"survey_id"`
	Answers  []byte `json:"answers"`
}

func (q *Queries) CreateSurveyResponse(ctx context.Context, arg CreateSurveyResponseParams) (SurveyResponse, error) {
	row := q.db.QueryRow(ctx, createSurveyResponse, arg.SurveyID, arg.Answers)
	var i SurveyResponse
	err := row.Scan(
		&i.ID,
		&i.SurveyID,
		&i.Answers,
		&i.CreatedAt,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (email, name, password_hash)
VALUES ($1, $2, $3)
RETURNING id, email, name, password_hash, created_at
`

type CreateUserParams struct {
	Email        string  `json:"email"`
	Name         *string `json:"name"`
	PasswordHash string  `json:"password_hash"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser, arg.Email, arg.Name, arg.PasswordHash)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getSurveyByID = `-- name: GetSurveyByID :one
SELECT id, title, description, questions, status, owner_id, created_at, updated_at
FROM surveys
WHERE id = $1
`

func (q *Queries) GetSurveyByID(ctx context.Context, id string) (Survey, error) {
	row := q.db.QueryRow(ctx, getSurveyByID, id)
	var i Survey
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Questions,
		&i.Status,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, password_hash, created_at
FROM users
WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, password_hash, created_at
FROM users
WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.PasswordHash,
		&i.CreatedAt,
	)
	return i, err
}

const listResponsesBySurvey = `-- name: ListResponsesBySurvey :many
SELECT id, survey_id, answers, created_at
FROM survey_responses
WHERE survey_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListResponsesBySurvey(ctx context.Context, surveyID string) ([]SurveyResponse, error) {
	rows, err := q.db.Query(ctx, listResponsesBySurvey, surveyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SurveyResponse{}
	for rows.Next() {
		var i SurveyResponse
		if err := rows.Scan(
			&i.ID,
			&i.SurveyID,
			&i.Answers,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSurveysByOwner = `-- name: ListSurveysByOwner :many
SELECT id, title, description, questions, status, owner_id, created_at, updated_at
FROM surveys
WHERE owner_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListSurveysByOwner(ctx context.Context, ownerID string) ([]Survey, error) {
	rows, err := q.db.Query(ctx, listSurveysByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Survey{}
	for rows.Next() {
		var i Survey
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Description,
			&i.Questions,
			&i.Status,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersByIDs = `-- name: ListUsersByIDs :many
SELECT id, email, name, password_hash, created_at
FROM users
WHERE id = ANY($1::text[])
`

func (q *Queries) ListUsersByIDs(ctx context.Context, dollar_1 []string) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.PasswordHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSurveyStatus = `-- name: UpdateSurveyStatus :one
UPDATE surveys
SET status = $2, updated_at = now()
WHERE id = $1 AND owner_id = $3
RETURNING id, title, description, questions, status, owner_id, created_at, updated_at
`

type UpdateSurveyStatusParams struct {
	ID      string `json:"id"`
	Status  string `json:"status"`
	OwnerID string `json:"owner_id"`
}

func (q *Queries) UpdateSurveyStatus(ctx context.Context, arg UpdateSurveyStatusParams) (Survey, error) {
	row := q.db.QueryRow(ctx, updateSurveyStatus, arg.ID, arg.Status, arg.OwnerID)
	var i Survey
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Description,
		&i.Questions,
		&i.Status,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
