package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.92

import (
	"context"
	"errors"

	"github.com/remake1/quicksurvey/api/graph/generated"
	"github.com/remake1/quicksurvey/api/graph/model"
	"github.com/remake1/quicksurvey/api/internal/domain"
	httpadapter "github.com/remake1/quicksurvey/api/internal/http"
	"github.com/remake1/quicksurvey/api/internal/infrastructure/dataloader"
	"github.com/remake1/quicksurvey/api/internal/usecase"
)

// CreateSurvey is the resolver for the createSurvey field.
func (r *mutationResolver) CreateSurvey(ctx context.Context, input model.CreateSurveyInput) (*model.Survey, error) {
	userID, err := requireUserID(ctx)
	if err != nil {
		return nil, err
	}
	survey, err := r.surveys.CreateSurvey(ctx, usecase.CreateSurveyInput{
		Title:       input.Title,
		Description: input.Description,
		Questions:   domainQuestions(input.Questions),
		OwnerID:     userID,
	})
	if err != nil {
		return nil, graphError(err)
	}
	return graphSurvey(survey), nil
}

// PublishSurvey is the resolver for the publishSurvey field.
func (r *mutationResolver) PublishSurvey(ctx context.Context, id string) (*model.Survey, error) {
	userID, err := requireUserID(ctx)
	if err != nil {
		return nil, err
	}
	survey, err := r.surveys.Publish(ctx, id, userID)
	if err != nil {
		return nil, graphError(err)
	}
	return graphSurvey(survey), nil
}

// UnpublishSurvey is the resolver for the unpublishSurvey field.
func (r *mutationResolver) UnpublishSurvey(ctx context.Context, id string) (*model.Survey, error) {
	userID, err := requireUserID(ctx)
	if err != nil {
		return nil, err
	}
	survey, err := r.surveys.Unpublish(ctx, id, userID)
	if err != nil {
		return nil, graphError(err)
	}
	return graphSurvey(survey), nil
}

// SubmitResponse is the resolver for the submitResponse field.
func (r *mutationResolver) SubmitResponse(ctx context.Context, input model.SubmitResponseInput) (*model.SurveyResponse, error) {
	response, err := r.surveys.SubmitResponse(ctx, usecase.SubmitResponseInput{
		SurveyID: input.SurveyID,
		Answers:  domainAnswers(input.Answers),
	})
	if err != nil {
		return nil, graphError(err)
	}
	return graphSurveyResponse(response), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	userID, ok := httpadapter.UserIDFromContext(ctx)
	if !ok {
		return nil, nil
	}
	user, err := r.auth.CurrentUser(ctx, userID)
	if err != nil {
		return nil, graphError(err)
	}
	return graphUser(user), nil
}

// Survey is the resolver for the survey field.
func (r *queryResolver) Survey(ctx context.Context, id string) (*model.Survey, error) {
	var viewerID *string
	if userID, ok := httpadapter.UserIDFromContext(ctx); ok {
		viewerID = &userID
	}
	survey, err := r.surveys.GetSurvey(ctx, id, viewerID)
	if err != nil {
		if errors.Is(err, domain.ErrNotFound) {
			return nil, nil
		}
		return nil, graphError(err)
	}
	return graphSurvey(survey), nil
}

// MySurveys is the resolver for the mySurveys field.
func (r *queryResolver) MySurveys(ctx context.Context) ([]*model.Survey, error) {
	userID, err := requireUserID(ctx)
	if err != nil {
		return nil, err
	}
	surveys, err := r.surveys.MySurveys(ctx, userID)
	if err != nil {
		return nil, graphError(err)
	}
	return graphSurveys(surveys), nil
}

// SurveyResponses is the resolver for the surveyResponses field.
func (r *queryResolver) SurveyResponses(ctx context.Context, surveyID string) ([]*model.SurveyResponse, error) {
	userID, err := requireUserID(ctx)
	if err != nil {
		return nil, err
	}
	responses, err := r.surveys.Responses(ctx, surveyID, userID)
	if err != nil {
		return nil, graphError(err)
	}
	return graphSurveyResponses(responses), nil
}

// Owner is the resolver for the owner field.
func (r *surveyResolver) Owner(ctx context.Context, obj *model.Survey) (*model.User, error) {
	if obj.Owner == nil || obj.Owner.ID == "" {
		return nil, graphError(domain.ErrNotFound)
	}
	loaders := dataloader.FromContext(ctx)
	if loaders == nil {
		user, err := r.users.FindByID(ctx, obj.Owner.ID)
		if err != nil {
			return nil, graphError(err)
		}
		return graphUser(user), nil
	}
	user, err := loaders.Users.Load(obj.Owner.ID)
	if err != nil {
		return nil, graphError(err)
	}
	return graphUser(user), nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

// Survey returns generated.SurveyResolver implementation.
func (r *Resolver) Survey() generated.SurveyResolver { return &surveyResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type surveyResolver struct{ *Resolver }
