// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Question interface {
	IsQuestion()
	GetID() string
	GetTitle() string
	GetRequired() bool
	GetType() QuestionType
}

type Answer struct {
	QuestionID     string       `json:"questionId"`
	Type           QuestionType `json:"type"`
	TextValue      *string      `json:"textValue,omitempty"`
	ChoiceValue    *string      `json:"choiceValue,omitempty"`
	CheckboxValues []string     `json:"checkboxValues,omitempty"`
	DateValue      *string      `json:"dateValue,omitempty"`
	ScaleValue     *int         `json:"scaleValue,omitempty"`
}

type AnswerInput struct {
	QuestionID     string       `json:"questionId"`
	Type           QuestionType `json:"type"`
	TextValue      *string      `json:"textValue,omitempty"`
	ChoiceValue    *string      `json:"choiceValue,omitempty"`
	CheckboxValues []string     `json:"checkboxValues,omitempty"`
	DateValue      *string      `json:"dateValue,omitempty"`
	ScaleValue     *int         `json:"scaleValue,omitempty"`
}

type CreateSurveyInput struct {
	Title       string           `json:"title"`
	Description *string          `json:"description,omitempty"`
	Questions   []*QuestionInput `json:"questions"`
}

type DateQuestion struct {
	ID       string       `json:"id"`
	Title    string       `json:"title"`
	Required bool         `json:"required"`
	Type     QuestionType `json:"type"`
}

func (DateQuestion) IsQuestion()                {}
func (this DateQuestion) GetID() string         { return this.ID }
func (this DateQuestion) GetTitle() string      { return this.Title }
func (this DateQuestion) GetRequired() bool     { return this.Required }
func (this DateQuestion) GetType() QuestionType { return this.Type }

type Mutation struct {
}

type Option struct {
	ID   string `json:"id"`
	Text string `json:"text"`
}

type OptionInput struct {
	ID   *string `json:"id,omitempty"`
	Text string  `json:"text"`
}

type OptionsQuestion struct {
	ID       string       `json:"id"`
	Title    string       `json:"title"`
	Required bool         `json:"required"`
	Type     QuestionType `json:"type"`
	Options  []*Option    `json:"options"`
}

func (OptionsQuestion) IsQuestion()                {}
func (this OptionsQuestion) GetID() string         { return this.ID }
func (this OptionsQuestion) GetTitle() string      { return this.Title }
func (this OptionsQuestion) GetRequired() bool     { return this.Required }
func (this OptionsQuestion) GetType() QuestionType { return this.Type }

type Query struct {
}

type QuestionInput struct {
	ID       *string        `json:"id,omitempty"`
	Title    string         `json:"title"`
	Required *bool          `json:"required,omitempty"`
	Type     QuestionType   `json:"type"`
	Options  []*OptionInput `json:"options,omitempty"`
	Min      *int           `json:"min,omitempty"`
	Max      *int           `json:"max,omitempty"`
	MinLabel *string        `json:"minLabel,omitempty"`
	MaxLabel *string        `json:"maxLabel,omitempty"`
}

type ScaleQuestion struct {
	ID       string       `json:"id"`
	Title    string       `json:"title"`
	Required bool         `json:"required"`
	Type     QuestionType `json:"type"`
	Min      int          `json:"min"`
	Max      int          `json:"max"`
	MinLabel *string      `json:"minLabel,omitempty"`
	MaxLabel *string      `json:"maxLabel,omitempty"`
}

func (ScaleQuestion) IsQuestion()                {}
func (this ScaleQuestion) GetID() string         { return this.ID }
func (this ScaleQuestion) GetTitle() string      { return this.Title }
func (this ScaleQuestion) GetRequired() bool     { return this.Required }
func (this ScaleQuestion) GetType() QuestionType { return this.Type }

type SubmitResponseInput struct {
	SurveyID string         `json:"surveyId"`
	Answers  []*AnswerInput `json:"answers"`
}

type Survey struct {
	ID          string       `json:"id"`
	Title       string       `json:"title"`
	Description *string      `json:"description,omitempty"`
	Questions   []Question   `json:"questions"`
	Status      SurveyStatus `json:"status"`
	Owner       *User        `json:"owner"`
	CreatedAt   time.Time    `json:"createdAt"`
	UpdatedAt   time.Time    `json:"updatedAt"`
}

type SurveyResponse struct {
	ID        string    `json:"id"`
	SurveyID  string    `json:"surveyId"`
	Answers   []*Answer `json:"answers"`
	CreatedAt time.Time `json:"createdAt"`
}

type TextQuestion struct {
	ID       string       `json:"id"`
	Title    string       `json:"title"`
	Required bool         `json:"required"`
	Type     QuestionType `json:"type"`
}

func (TextQuestion) IsQuestion()                {}
func (this TextQuestion) GetID() string         { return this.ID }
func (this TextQuestion) GetTitle() string      { return this.Title }
func (this TextQuestion) GetRequired() bool     { return this.Required }
func (this TextQuestion) GetType() QuestionType { return this.Type }

type User struct {
	ID        string    `json:"id"`
	Email     string    `json:"email"`
	Name      *string   `json:"name,omitempty"`
	CreatedAt time.Time `json:"createdAt"`
}

type QuestionType string

const (
	QuestionTypeShortAnswer    QuestionType = "short_answer"
	QuestionTypeParagraph      QuestionType = "paragraph"
	QuestionTypeMultipleChoice QuestionType = "multiple_choice"
	QuestionTypeCheckboxes     QuestionType = "checkboxes"
	QuestionTypeDropdown       QuestionType = "dropdown"
	QuestionTypeDate           QuestionType = "date"
	QuestionTypeLinearScale    QuestionType = "linear_scale"
)

var AllQuestionType = []QuestionType{
	QuestionTypeShortAnswer,
	QuestionTypeParagraph,
	QuestionTypeMultipleChoice,
	QuestionTypeCheckboxes,
	QuestionTypeDropdown,
	QuestionTypeDate,
	QuestionTypeLinearScale,
}

func (e QuestionType) IsValid() bool {
	switch e {
	case QuestionTypeShortAnswer, QuestionTypeParagraph, QuestionTypeMultipleChoice, QuestionTypeCheckboxes, QuestionTypeDropdown, QuestionTypeDate, QuestionTypeLinearScale:
		return true
	}
	return false
}

func (e QuestionType) String() string {
	return string(e)
}

func (e *QuestionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = QuestionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid QuestionType", str)
	}
	return nil
}

func (e QuestionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *QuestionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e QuestionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type SurveyStatus string

const (
	SurveyStatusDraft     SurveyStatus = "DRAFT"
	SurveyStatusPublished SurveyStatus = "PUBLISHED"
)

var AllSurveyStatus = []SurveyStatus{
	SurveyStatusDraft,
	SurveyStatusPublished,
}

func (e SurveyStatus) IsValid() bool {
	switch e {
	case SurveyStatusDraft, SurveyStatusPublished:
		return true
	}
	return false
}

func (e SurveyStatus) String() string {
	return string(e)
}

func (e *SurveyStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = SurveyStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid SurveyStatus", str)
	}
	return nil
}

func (e SurveyStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *SurveyStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e SurveyStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
